#!/bin/bash
# postinst script for indi2mqtt

# enable and start service
if [ -x /run/systemd/system ]; then
    sudo systemctl daemon-reload
    systemctl enable indi2mqtt.service
    systemctl start indi2mqtt.service
fi
